routes/web.php
<?php

use App\Http\Livewire\Home\ProgramComponent;
use App\Http\Livewire\Home\WelcomeComponent;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'App\Http\Controllers\HomeController@index')->name('home');

Route::get('/all', 'App\Http\Controllers\HomeController@all')->name('all');

Route::get('/fin', 'App\Http\Controllers\HomeController@fin')->name('fin');

Route::get('/contacts', 'App\Http\Controllers\HomeController@contacts')->name('contacts');

Route::get('/math', 'App\Http\Controllers\HomeController@math')->name('math');

Route::get('/news','App\Http\Controllers\HomeController@news' )->name('news');

Route::get('/news/{slug}', 'App\Http\Controllers\HomeController@newsShow' )->name('news.show');

Route::get('/prog', 'App\Http\Controllers\HomeController@prog')->name('prog');

Route::get('/about', 'App\Http\Controllers\HomeController@about')->name('about');

Route::get('/stud', 'App\Http\Controllers\HomeController@stud')->name('stud');


Route::get('/schedule', 'App\Http\Controllers\HomeController@schedule')->name('schedule');

Route::middleware(['auth:sanctum', 'verified'])->prefix('/admin')->namespace('App\Http\Controllers\Admin')
    ->name('admin.')
    ->group(function () {
        Route::get('/dashboard', function () {
            return view('dashboard');
        })->name('dashboard');

        Route::get('/', function () {
            Storage::deleteDirectory('livewire-tmp');
            return redirect()->route('admin.contact.index');
        })->name('index');

        Route::prefix('home/')->name('home.')->group(function () {
            Route::get('/', 'HomeController@index')->name('index');
        });

        Route::prefix('/contact')->name('contact.')->group(function () {
            Route::get('/', 'ContactController@index')->name('index');
            Route::get('/{contact}/delete', 'ContactController@delete')->name('delete');
            Route::get('/create', 'ContactController@create')->name('create');
            Route::post('/', 'ContactController@store')->name('index');
            Route::get('/{contact}/edit', 'ContactController@edit')->name('edit');
            Route::put('/{contact}/update', 'ContactController@update')->name('update');
        });

        Route::prefix('/category')->name('category.')->group(function () {
            Route::get('/', 'CategoryController@index')->name('index');
            Route::get('/create', 'CategoryController@create')->name('create');
            Route::post('/', 'CategoryController@store')->name('index');
            Route::get('/{category}/edit', 'CategoryController@edit')->name('edit');
            Route::put('/{category}', 'CategoryController@update')->name('update');
            Route::get('/{category}/delete', 'CategoryController@destroy')->name('delete');
        });

        Route::prefix('/course')->name('course.')->group(function () {
            Route::get('/', 'CourseController@index')->name('index');
            Route::get('/create', 'CourseController@create')->name('create');
            Route::post('/', 'CourseController@store')->name('index');
            Route::get('/{course}/edit', 'CourseController@edit')->name('edit');
            Route::put('/{course}', 'CourseController@update')->name('update');
            Route::get('/{course}/delete', 'CourseController@destroy')->name('delete');
        });

    });

Route::middleware(['auth:sanctum', 'verified'])->prefix('/admin')->name('admin.')->group(function () {


    Route::get('/default/{model}/{block}', \App\Http\Livewire\About\DefaultComponent::class)->name('default');
    Route::get('/feature/{model}', \App\Http\Livewire\Home\FeatureComponent::class)->name('feature');
    Route::get('/content/{model}', \App\Http\Livewire\ContentComponent::class)->name('content');

    Route::prefix('home/')->name('home.')->group(function () {
        Route::get('/program', ProgramComponent::class)->name('program');
        Route::get('/welcome', WelcomeComponent::class)->name('welcome');
        Route::get('/help', \App\Http\Livewire\Home\HelpComponent::class)->name('help');
        Route::get('/logo', \App\Http\Livewire\Home\LogoComponent::class)->name('logo');
        Route::get('/footer', \App\Http\Livewire\Home\FooterComponent::class)->name('footer');
    });


    Route::prefix('video/')->name('video.')->group(function () {
        Route::get('{name}', \App\Http\Livewire\VideoComponent::class)->name('index');
    });


    Route::prefix('about/')->name('about.')->group(function () {
        Route::get('/feature', \App\Http\Livewire\About\FeatureComponent::class)->name('feature');
        Route::get('/staff', \App\Http\Livewire\About\StaffComponent::class)->name('staff');
    });

    Route::prefix('prog/')->name('prog.')->group(function () {
        Route::get('/advantage', \App\Http\Livewire\ProgAdvantageComponent::class)->name('advantage');
    });

    Route::prefix('schedule/')->name('schedule.')->group(function () {
        Route::get('/edit/{course}', \App\Http\Livewire\ScheduleComponent::class)->name('edit');
    });

    Route::prefix('articles/')->name('article.')->group(function () {
        Route::get('/create', \App\Http\Livewire\AddArticleComponent::class)->name('create');
        Route::get('/edit/{article}', \App\Http\Livewire\AddArticleComponent::class)->name('edit');

        Route::get('/{type}', \App\Http\Livewire\AllArticlesComponent::class)->name('index');
    });

});

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\CourseCategory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;
use PhpParser\Node\Stmt\DeclareDeclare;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index()
    {
        $categories = CourseCategory::latest()->paginate(10);

        return view('admin.category.index',
            [
                'categories' => $categories
            ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return RedirectResponse
     */
    public function store()
    {
        CourseCategory::create($this->validateCategory());
        return redirect()
            ->route('admin.category.index')
            ->with('success', __('position.messages.success_created'));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param CourseCategory $category
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit(CourseCategory $category)
    {
        return view('admin.category.edit',
            [
                'category' => $category
            ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CourseCategory $category
     * @return RedirectResponse
     */
    public function update(CourseCategory $category)
    {
        $category->update($this->validateCategory());
        return redirect()
            ->route('admin.category.index')
            ->with('success', __('position.messages.success_updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param CourseCategory $category
     * @return RedirectResponse
     * @throws \Exception
     */
    public function destroy(CourseCategory $category)
    {
        $category->delete();
        return redirect()->route('admin.category.index');
    }

    protected function validateCategory()
    {
        return request()->validate(
            [
                'title_en' => 'required|string|max:255',
                'title_ru' => 'required|string|max:255',
            ]
        );
    }
}

resources/views/admin/category/create.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="card">
        <div class="card-header">
            <h1>Добавить категорию</h1>        </div>
        <form method="POST" action="{{route('admin.category.index')}}" enctype="multipart/form-data">
            @csrf
            <div class="card-body">

                <div class="form-group">
                    <label class="label" for="title_ru">
                        Заголовок
                    </label>

                    <div class="control">
                        <input type="text"
                               class="form-control @error('title_ru') is-invalid @enderror"
                               name="title_ru"
                               id="title_ru"
                               value="{{old('title_ru')}}"
                               required>
                    </div>

                    @error('title_ru')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="form-group">
                    <label class="label" for="title_en">
                        Title
                    </label>
                    <div class="control">
                        <input type="text"
                               class="form-control @error('title_en') is-invalid @enderror"
                               name="title_en"
                               id="title_en"
                               value="{{old('title_en')}}"
                               required>
                    </div>

                    @error('title_en')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>


            </div>
            <div class="card-footer">
                <div class="form-group">
                    <div class="control">
                        <button class="btn btn-success float-right" type="submit">Сохранить</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/category/edit.blade.php
@extends('admin.layouts.main')
@section('content')
    <div class="card">
        <div class="card-header">
            <h1>Редактировать категорию</h1>
        </div>
        <form method="POST" action="{{route('admin.category.update',$category->id)}}" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="card-body">


                <div class="form-group">
                    <label class="label" for="title_ru">
                        Заголовок
                    </label>

                    <div class="control">
                        <input type="text"
                               class="form-control @error('title_ru') is-invalid @enderror"
                               name="title_ru"
                               id="title_ru"
                               value="{{$category->title_ru}}"
                               required>

                    </div>

                    @error('title_ru')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>


                <div class="form-group">
                    <label class="label" for="title_en">
                        Title
                    </label>

                    <div class="control">
                        <input type="text"
                               class="form-control @error('title_en') is-invalid @enderror"
                               name="title_en"
                               id="title_en"
                               value="{{$category->title_en}}"
                               required>

                    </div>

                    @error('title_en')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>


            </div>
            <div class="card-footer">
                <div class="form-group">
                    <div class="control">
                        <button class="btn btn-success float-right" type="submit">Сохранить</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/category/index.blade.php
@extends('admin.layouts.main')

@section('content')
    <div>
        <div class="card">
            <div class="card-header">
                <div class="d-flex justify-content-between mt-3">
                    <h2>Категории курсов</h2>
                    <a href="{{route('admin.category.create')}}" class="btn btn-success mb-2">Добавить</a>
                </div>
            </div>
            <div class="card-body">
                <div class="table table-responsive">
                    <table class="table table-hover">
                        <thead>

                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Заголовок</th>
                            <th scope="col">Title</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody class="">
                        @foreach($categories as $index=>$category)
                            <tr>
                                <th scope="row"><a
                                        href="{{route('admin.category.edit',$category->id)}}">{{$index+1}} </a>
                                </th>
                                <th scope="row"><a
                                        href="{{route('admin.category.edit',$category->id)}}">{{$category->title_ru}} </a>
                                </th>
                                <th scope="row"><a
                                        href="{{route('admin.category.edit',$category->id)}}">{{$category->title_en}} </a>
                                </th>
                                <td><a onclick="return confirm('Are you sure?')"
                                       href="{{route('admin.category.delete',$category)}}"><i
                                            class="fa fa-trash fa-fw"></i></a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>

                    </table>

                </div>
            </div>
            <div class="card-footer">
                {{ $categories->links() }}
            </div>
        </div>
    </div>

@endsection