routes/web.php
<?php

use App\Http\Livewire\Home\ProgramComponent;
use App\Http\Livewire\Home\WelcomeComponent;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'App\Http\Controllers\HomeController@index')->name('home');

Route::get('/all', 'App\Http\Controllers\HomeController@all')->name('all');

Route::get('/fin', 'App\Http\Controllers\HomeController@fin')->name('fin');

Route::get('/contacts', 'App\Http\Controllers\HomeController@contacts')->name('contacts');

Route::get('/math', 'App\Http\Controllers\HomeController@math')->name('math');

Route::get('/news','App\Http\Controllers\HomeController@news' )->name('news');

Route::get('/news/{slug}', 'App\Http\Controllers\HomeController@newsShow' )->name('news.show');

Route::get('/prog', 'App\Http\Controllers\HomeController@prog')->name('prog');

Route::get('/about', 'App\Http\Controllers\HomeController@about')->name('about');

Route::get('/stud', 'App\Http\Controllers\HomeController@stud')->name('stud');


Route::get('/schedule', 'App\Http\Controllers\HomeController@schedule')->name('schedule');

Route::middleware(['auth:sanctum', 'verified'])->prefix('/admin')->namespace('App\Http\Controllers\Admin')
    ->name('admin.')
    ->group(function () {
        Route::get('/dashboard', function () {
            return view('dashboard');
        })->name('dashboard');

        Route::get('/', function () {
            Storage::deleteDirectory('livewire-tmp');
            return redirect()->route('admin.contact.index');
        })->name('index');

        Route::prefix('home/')->name('home.')->group(function () {
            Route::get('/', 'HomeController@index')->name('index');
        });

        Route::prefix('/contact')->name('contact.')->group(function () {
            Route::get('/', 'ContactController@index')->name('index');
            Route::get('/{contact}/delete', 'ContactController@delete')->name('delete');
            Route::get('/create', 'ContactController@create')->name('create');
            Route::post('/', 'ContactController@store')->name('index');
            Route::get('/{contact}/edit', 'ContactController@edit')->name('edit');
            Route::put('/{contact}/update', 'ContactController@update')->name('update');
        });

        Route::prefix('/category')->name('category.')->group(function () {
            Route::get('/', 'CategoryController@index')->name('index');
            Route::get('/create', 'CategoryController@create')->name('create');
            Route::post('/', 'CategoryController@store')->name('index');
            Route::get('/{category}/edit', 'CategoryController@edit')->name('edit');
            Route::put('/{category}', 'CategoryController@update')->name('update');
            Route::get('/{category}/delete', 'CategoryController@destroy')->name('delete');
        });

        Route::prefix('/course')->name('course.')->group(function () {
            Route::get('/', 'CourseController@index')->name('index');
            Route::get('/create', 'CourseController@create')->name('create');
            Route::post('/', 'CourseController@store')->name('index');
            Route::get('/{course}/edit', 'CourseController@edit')->name('edit');
            Route::put('/{course}', 'CourseController@update')->name('update');
            Route::get('/{course}/delete', 'CourseController@destroy')->name('delete');
        });

    });

Route::middleware(['auth:sanctum', 'verified'])->prefix('/admin')->name('admin.')->group(function () {


    Route::get('/default/{model}/{block}', \App\Http\Livewire\About\DefaultComponent::class)->name('default');
    Route::get('/feature/{model}', \App\Http\Livewire\Home\FeatureComponent::class)->name('feature');
    Route::get('/content/{model}', \App\Http\Livewire\ContentComponent::class)->name('content');

    Route::prefix('home/')->name('home.')->group(function () {
        Route::get('/program', ProgramComponent::class)->name('program');
        Route::get('/welcome', WelcomeComponent::class)->name('welcome');
        Route::get('/help', \App\Http\Livewire\Home\HelpComponent::class)->name('help');
        Route::get('/logo', \App\Http\Livewire\Home\LogoComponent::class)->name('logo');
        Route::get('/footer', \App\Http\Livewire\Home\FooterComponent::class)->name('footer');
    });


    Route::prefix('video/')->name('video.')->group(function () {
        Route::get('{name}', \App\Http\Livewire\VideoComponent::class)->name('index');
    });


    Route::prefix('about/')->name('about.')->group(function () {
        Route::get('/feature', \App\Http\Livewire\About\FeatureComponent::class)->name('feature');
        Route::get('/staff', \App\Http\Livewire\About\StaffComponent::class)->name('staff');
    });

    Route::prefix('prog/')->name('prog.')->group(function () {
        Route::get('/advantage', \App\Http\Livewire\ProgAdvantageComponent::class)->name('advantage');
    });

    Route::prefix('schedule/')->name('schedule.')->group(function () {
        Route::get('/edit/{course}', \App\Http\Livewire\ScheduleComponent::class)->name('edit');
    });

    Route::prefix('articles/')->name('article.')->group(function () {
        Route::get('/create', \App\Http\Livewire\AddArticleComponent::class)->name('create');
        Route::get('/edit/{article}', \App\Http\Livewire\AddArticleComponent::class)->name('edit');

        Route::get('/{type}', \App\Http\Livewire\AllArticlesComponent::class)->name('index');
    });

});

app/Models/Contact.php
<?php

namespace App\Models;

use App\Traits\Multilingual;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    use HasFactory, Multilingual;

    protected $guarded = ['id'];

    const MOBILE = 0;
    const ADDRESS = 1;
    const TEXT = 2;
    const INTSA = 3;
    const YOUTUBE = 4;
    const FACEBOOK = 5;


    public function getTypeTitleAttribute()
    {
        switch ($this->attributes['type']) {
            case self::MOBILE:
                return 'Телефон';
                break;
            case self::ADDRESS:
                return 'Адрес';
                break;
            case self::TEXT:
                return 'Текст';
                break;
            case self::INTSA:
                return 'Instagram';
                break;
            case self::FACEBOOK:
                return 'Facebook';
                break;
            case self::YOUTUBE:
                return 'Youtube';
                break;
        }

        return $this->type;
    }


    public static function getTypeList()
    {
        return [
            self::MOBILE => 'Телефон',
            self::TEXT => 'Текст',
            self::ADDRESS => 'Адрес',
            self::INTSA => 'Instagram',
            self::FACEBOOK => 'Facebook',
            self::YOUTUBE => 'Youtube',
        ];
    }
}

app/Http/Controllers/Admin/ContactController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Contact;
use App\Models\ContactInformation;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ContactController extends Controller
{
    public function index()
    {
        Storage::deleteDirectory('livewire-tmp');

        return view('admin.contact.index',
            [
                'contacts' => Contact::all()]);
    }

    public function create()
    {
        return view('admin.contact.create');
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'content_ru' => 'nullable|string|max:255',
            'content_en' => 'nullable|string|max:255',
            'type' => 'nullable|integer|digits:1',
        ]);

        Contact::create($validatedData);

        return redirect()->route('admin.contact.index');

    }

    public function edit(Contact $contact)
    {
        return view('admin.contact.edit',
            [
                'contact' => $contact
            ]);

    }

    public function update(Request $request, Contact $contact)
    {
        $validatedData = $request->validate([
            'content_ru' => 'nullable|string|max:255',
            'content_en' => 'nullable|string|max:255',
            'type' => 'nullable|integer',
        ]);

        $contact->update($validatedData);

        return redirect()->route('admin.contact.index');
    }

    public function delete(Contact $contact)
    {
        $contact->delete();
        return redirect()->route('admin.contact.index');
    }

}

resources/views/admin/contact/create.blade.php
@extends('admin.layouts.main')
@section('content')
    <div>
        <div class="card ">

            <form method="POST" action="{{route('admin.contact.index')}}" enctype="multipart/form-data">
                @csrf
                <div class="card-body">

                    <div class="form-group">
                        <label for="content">Контент</label>
                        <input name="content_ru" type="text" class="form-control" id="content_ru"
                               value="{{old('content_ru')}}"
                        >
                        @error('content_ru')
                        <div class="text-red">{{$message}}</div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="content">Content</label>
                        <input name="content_en" type="text" class="form-control" id="content_en"
                               value="{{old('content_en')}}"
                        >
                        @error('content_en')
                        <div class="text-red">{{$message}}</div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label class="label" for="type">
                            Тип
                        </label>

                        <div class="control">
                            <select class="form-control" id="type" name="type" required>
                                <option value="" selected disabled>Тип</option>
                                @foreach(\App\Models\Contact::getTypeList() as $index=>$type)
                                    <option
                                        value="{{$index}}">{{$type}}</option>
                                @endforeach
                            </select>

                        </div>

                        @error('type')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>


{{--                    <div id="map" style="width: 100%; height: 250px"></div>--}}


                </div>
                <div class="card-footer">
                    <div class="form-group">
                        <button type="submit"
                                class="btn btn-success d-inline-flex align-items-center justify-content-center">
                            Сохранить
                        </button>
                    </div>
                </div>
            </form>

        </div>
    </div>

@endsection
{{--<script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>--}}

{{--@push('scripts')--}}
{{--    <script>--}}
{{--        ymaps.ready(init);--}}
{{--        var center_map = [0, 0];--}}
{{--        var map = "";--}}

{{--        function init() {--}}
{{--            map = new ymaps.Map('map', {--}}
{{--                center: [43.235908367466486, 76.95276060852048],--}}
{{--                zoom: 12,--}}
{{--            });--}}


{{--            map.setCenter([43.235908367466486,76.95276060852048]);--}}

{{--            map.geoObjects.add(new ymaps.Placemark([43.235908367466486, 76.95276060852048], {--}}
{{--                balloonContent: '',--}}

{{--            }, {--}}
{{--                preset: 'islands#icon',--}}
{{--                apikey:'695b3c94-4e87-4f93-b7c7-a49c3cfb89d8\n',--}}
{{--                iconColor: '#0095b6'--}}
{{--            }));--}}


{{--            map.events.add('click', function (e) {--}}
{{--                console.log(e.get('coords'));--}}
{{--                map.geoObjects.removeAll();--}}
{{--                var coords = e.get('coords');--}}
{{--                map.geoObjects.add(new ymaps.Placemark(coords, {--}}
{{--                    balloonContent: ''--}}
{{--                }, {--}}
{{--                    preset: 'islands#icon',--}}
{{--                    iconColor: '#0095b6'--}}
{{--                }));--}}

{{--                $("#address-latitude").val(coords[0].toPrecision(9));--}}
{{--                $("#address-longitude").val(coords[1].toPrecision(9));--}}


{{--            });--}}
{{--        }--}}
{{--    </script>--}}

{{--@endpush--}}

resources/views/admin/contact/edit.blade.php
@extends('admin.layouts.main')

@section('content')

    <div>
        <div class="card ">
            <form method="POST" action="{{route('admin.contact.update',$contact)}}" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="card-body">
                    <div class="form-group">
                        <label for="content">Контент</label>
                        <input name="content" type="text" class="form-control" id="content_ru"
                               value="{{$contact->content_ru}}"
                        >
                        @error('content_ru')
                        <div class="text-red">{{$message}}</div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="content">Content</label>
                        <input name="content" type="text" class="form-control" id="content_en"
                               value="{{$contact->content_en}}"
                        >
                        @error('content_en')
                        <div class="text-red">{{$message}}</div>
                        @enderror
                    </div>


                    <div class="form-group">
                        <label class="label" for="type">
                            Тип
                        </label>

                        <div class="control">
                            <select class="form-control" id="type" name="type" required>
                                <option value="" selected disabled>Тип</option>
                                @foreach(\App\Models\Contact::getTypeList() as $index=>$type)
                                    <option
                                        @if($contact->type == $index)selected
                                        @endif
                                        value="{{$index}}">{{$type}}</option>
                                @endforeach
                            </select>

                        </div>

                        @error('type')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>

                </div>
                <div class="card-footer">
                    <div class="form-group">
                        <button type="submit"
                                class="btn btn-success d-inline-flex align-items-center justify-content-center">
                            Сохранить
                        </button>
                    </div>
                </div>
            </form>

        </div>
    </div>
@endsection()

resources/views/admin/contact/index.blade.php
@extends('admin.layouts.main')

@section('content')
    <div>
        <div class="card">
            <div class="card-header">
                <div class="d-flex justify-content-between">
                    <h2>Контакты</h2>
                    <a href="{{route('admin.contact.create')}}"
                       class="btn btn-success mb-2">Добавить</a>
                </div>
            </div>
            <div class="card-body">
                <div class="table table-responsive">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Контент</th>
                            <th scope="col">Тип</th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody class="">
                        @foreach($contacts as $index=>$contact)
                            <tr>
                                <th scope="row"><a
                                        href="{{route('admin.contact.edit',$contact->id)}}">{{$index+1}} </a>
                                </th>
                                <th scope="row">
                                    <a
                                        href="{{route('admin.contact.edit',$contact->id)}}">{{$contact->content}} </a>
                                </th>
                                <th scope="row">
                                    <a
                                        href="{{route('admin.contact.edit',$contact->id)}}">{{$contact->typeTitle}} </a>
                                </th>
                                <td><a
                                        href="{{route('admin.contact.edit',$contact->id)}}"><i
                                            class="fa fa-pen fa-fw"></i></a>
                                </td>

                                <td><a onclick="return confirm('Вы уверены?')"
                                       href="{{route('admin.contact.delete',$contact)}}"><i
                                            class="fa fa-trash fa-fw"></i></a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

@endsection