routes/web.php
<?php

use App\Http\Livewire\Home\ProgramComponent;
use App\Http\Livewire\Home\WelcomeComponent;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'App\Http\Controllers\HomeController@index')->name('home');

Route::get('/all', 'App\Http\Controllers\HomeController@all')->name('all');

Route::get('/fin', 'App\Http\Controllers\HomeController@fin')->name('fin');

Route::get('/contacts', 'App\Http\Controllers\HomeController@contacts')->name('contacts');

Route::get('/math', 'App\Http\Controllers\HomeController@math')->name('math');

Route::get('/news','App\Http\Controllers\HomeController@news' )->name('news');

Route::get('/news/{slug}', 'App\Http\Controllers\HomeController@newsShow' )->name('news.show');

Route::get('/prog', 'App\Http\Controllers\HomeController@prog')->name('prog');

Route::get('/about', 'App\Http\Controllers\HomeController@about')->name('about');

Route::get('/stud', 'App\Http\Controllers\HomeController@stud')->name('stud');


Route::get('/schedule', 'App\Http\Controllers\HomeController@schedule')->name('schedule');

Route::middleware(['auth:sanctum', 'verified'])->prefix('/admin')->namespace('App\Http\Controllers\Admin')
    ->name('admin.')
    ->group(function () {
        Route::get('/dashboard', function () {
            return view('dashboard');
        })->name('dashboard');

        Route::get('/', function () {
            Storage::deleteDirectory('livewire-tmp');
            return redirect()->route('admin.contact.index');
        })->name('index');

        Route::prefix('home/')->name('home.')->group(function () {
            Route::get('/', 'HomeController@index')->name('index');
        });

        Route::prefix('/contact')->name('contact.')->group(function () {
            Route::get('/', 'ContactController@index')->name('index');
            Route::get('/{contact}/delete', 'ContactController@delete')->name('delete');
            Route::get('/create', 'ContactController@create')->name('create');
            Route::post('/', 'ContactController@store')->name('index');
            Route::get('/{contact}/edit', 'ContactController@edit')->name('edit');
            Route::put('/{contact}/update', 'ContactController@update')->name('update');
        });

        Route::prefix('/category')->name('category.')->group(function () {
            Route::get('/', 'CategoryController@index')->name('index');
            Route::get('/create', 'CategoryController@create')->name('create');
            Route::post('/', 'CategoryController@store')->name('index');
            Route::get('/{category}/edit', 'CategoryController@edit')->name('edit');
            Route::put('/{category}', 'CategoryController@update')->name('update');
            Route::get('/{category}/delete', 'CategoryController@destroy')->name('delete');
        });

        Route::prefix('/course')->name('course.')->group(function () {
            Route::get('/', 'CourseController@index')->name('index');
            Route::get('/create', 'CourseController@create')->name('create');
            Route::post('/', 'CourseController@store')->name('index');
            Route::get('/{course}/edit', 'CourseController@edit')->name('edit');
            Route::put('/{course}', 'CourseController@update')->name('update');
            Route::get('/{course}/delete', 'CourseController@destroy')->name('delete');
        });

    });

Route::middleware(['auth:sanctum', 'verified'])->prefix('/admin')->name('admin.')->group(function () {


    Route::get('/default/{model}/{block}', \App\Http\Livewire\About\DefaultComponent::class)->name('default');
    Route::get('/feature/{model}', \App\Http\Livewire\Home\FeatureComponent::class)->name('feature');
    Route::get('/content/{model}', \App\Http\Livewire\ContentComponent::class)->name('content');

    Route::prefix('home/')->name('home.')->group(function () {
        Route::get('/program', ProgramComponent::class)->name('program');
        Route::get('/welcome', WelcomeComponent::class)->name('welcome');
        Route::get('/help', \App\Http\Livewire\Home\HelpComponent::class)->name('help');
        Route::get('/logo', \App\Http\Livewire\Home\LogoComponent::class)->name('logo');
        Route::get('/footer', \App\Http\Livewire\Home\FooterComponent::class)->name('footer');
    });


    Route::prefix('video/')->name('video.')->group(function () {
        Route::get('{name}', \App\Http\Livewire\VideoComponent::class)->name('index');
    });


    Route::prefix('about/')->name('about.')->group(function () {
        Route::get('/feature', \App\Http\Livewire\About\FeatureComponent::class)->name('feature');
        Route::get('/staff', \App\Http\Livewire\About\StaffComponent::class)->name('staff');
    });

    Route::prefix('prog/')->name('prog.')->group(function () {
        Route::get('/advantage', \App\Http\Livewire\ProgAdvantageComponent::class)->name('advantage');
    });

    Route::prefix('schedule/')->name('schedule.')->group(function () {
        Route::get('/edit/{course}', \App\Http\Livewire\ScheduleComponent::class)->name('edit');
    });

    Route::prefix('articles/')->name('article.')->group(function () {
        Route::get('/create', \App\Http\Livewire\AddArticleComponent::class)->name('create');
        Route::get('/edit/{article}', \App\Http\Livewire\AddArticleComponent::class)->name('edit');

        Route::get('/{type}', \App\Http\Livewire\AllArticlesComponent::class)->name('index');
    });

});

app/Http/Livewire/About/DefaultComponent.php
<?php

namespace App\Http\Livewire\About;

use App\Models\About;
use App\Models\Engineer;
use App\Models\Everyone;
use App\Models\Fin;
use App\Models\Prog;
use App\Models\Schedule;
use App\Models\Stud;
use Livewire\Component;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class DefaultComponent extends Component
{
    public $model;
    public $title_ru;
    public $title_en;
    public $content_en;
    public $content_ru;

    protected $rules = [
        'title_ru' => 'nullable|string|max:255',
        'title_en' => 'nullable|string|max:255',
        'content_ru' => 'nullable|string',
        'content_en' => 'nullable|string',
    ];

    public function render()
    {
        return view('livewire.about.default-component')->layout('admin.layouts.app');
    }

    public function mount($model, $block)
    {

        throw_unless(in_array(mb_strtoupper($model), ['ABOUT', 'FIN', 'PROG', 'STUD', 'EVERYONE', 'ENGINEER', 'SCHEDULE']), NotFoundHttpException::class);
        if (mb_strtoupper($model) == 'ABOUT') {
            throw_unless(in_array(mb_strtoupper($block), [About::BEAUTY, About::EASY, About::DEV, About::AVAILABLE]), NotFoundHttpException::class);
            $item = About::where('block', $block)->first();
        } elseif (mb_strtoupper($model) == 'FIN') {
            throw_unless(in_array(mb_strtoupper($block), [Fin::INFO, Fin::DEMAND, Fin::PROGS]), NotFoundHttpException::class);
            $item = Fin::where('block', $block)->first();
        } elseif (mb_strtoupper($model) == 'PROG') {
            throw_unless(in_array(mb_strtoupper($block), [Prog::ART, Prog::GOOD, Prog::IQ, Prog::ML, Prog::CORP]), NotFoundHttpException::class);
            $item = PROG::where('block', $block)->first();
        } elseif (mb_strtoupper($model) == 'STUD') {
            throw_unless(in_array(mb_strtoupper($block), [Stud::TRUTH, Stud::OFFER, Stud::HELP, Stud::HIGH, Stud::STUDENT]), NotFoundHttpException::class);
            $item = Stud::where('block', $block)->first();
        } elseif (mb_strtoupper($model) == 'ENGINEER') {
            throw_unless(in_array(mb_strtoupper($block), [1, 2, 3, 5]), NotFoundHttpException::class);
            $item = ENGINEER::where('block', $block)->first();
        } elseif (mb_strtoupper($model) == 'EVERYONE') {
            throw_unless(in_array(mb_strtoupper($block), [1, 2, 3]), NotFoundHttpException::class);
            $item = EVERYONE::where('block', $block)->first();
        } elseif (mb_strtoupper($model) == 'SCHEDULE') {
            throw_unless(in_array(mb_strtoupper($block), [0]), NotFoundHttpException::class);
            $item = Schedule::where('block', $block)->first();
        }


        $this->model = $item;
        $this->title_ru = $item->title_ru;
        $this->title_en = $item->title_en;
        $this->content_ru = $item->content_ru;
        $this->content_en = $item->content_en;

    }

    public function store()
    {
        $this->model->update($this->validate());
        session()->flash('message', 'Успех!');
    }
}

app/Http/Livewire/About/FeatureComponent.php
<?php

namespace App\Http\Livewire\About;

use App\Models\About;
use Livewire\Component;

class FeatureComponent extends Component
{
    public $features = [];

    protected $rules = [
        'features' => 'array|min:1',
        'features.*.title_ru' => 'required|string|max:255',
        'features.*.title_en' => 'required|string|max:255',
    ];


    public function render()
    {
        return view('livewire.about.feature-component')->layout('admin.layouts.app');
    }

    public function mount()
    {
        $features = About::where('block', About::FEATURE)->get();
        if ($features->isNotEmpty()) {
            $features->each(function ($item) {
                $this->features[] =
                    [
                        'id' => $item->id,
                        'title_ru' => $item->title_ru,
                        'title_en' => $item->title_en,
                    ];
            })->toArray();

        } else {
            $this->add();
        }
    }

    public function remove($key)
    {
        if (array_key_exists('id', $this->features[$key])) {
            About::find($this->features[$key]['id'])->delete();
        }
        unset($this->features[$key]);
        $this->features = array_values($this->features);
    }

    public function add()
    {
        $this->features[] = [
            'title_ru' => '',
            'title_en' => ''
        ];
    }

    public function store()
    {
        $validatedData = $this->validate();

        foreach ($this->features as $key => $feature) {
            if (array_key_exists('id', $feature)) {
                $old = About::find($this->features[$key]['id']);
                $old->update($validatedData['features'][$key]);
                $old->save();
            } else {
                $new = new About();
                $new->title_ru = $feature['title_ru'];
                $new->title_en = $feature['title_en'];
                $new->block = About::FEATURE;
                $new->save();
            }
        }

        session()->flash('message', 'Успех!');
        return redirect()->route('admin.about.feature');

    }


}

app/Http/Livewire/About/StaffComponent.php
<?php

namespace App\Http\Livewire\About;

use App\Models\About;
use Illuminate\Support\Facades\Storage;
use Livewire\Component;
use Livewire\WithFileUploads;

class StaffComponent extends Component
{
    use WithFileUploads;
    public $employees = [];
    public $images = [];
    public $empIds = [];

    protected $rules = [
        'employees' => 'array|min:1',
        'employees.*.title_ru' => 'required|string|max:255',
        'employees.*.title_en' => 'required|string|max:255',
        'employees.*.content_ru' => 'required|string',
        'employees.*.content_en' => 'required|string',
    ];

    public function render()
    {

        return view('livewire.about.staff-component')->layout('admin.layouts.app');
    }

    public function mount()
    {
        $employees = About::where('block', About::STAFF)->get();
        if ($employees->isNotEmpty()) {
            $employees->each(function ($item) {
                $this->employees[] =
                    [
                        'id' => $item->id,
                        'title_ru' => $item->title_ru,
                        'title_en' => $item->title_en,
                        'content_ru' => $item->content_ru,
                        'content_en' => $item->content_en,
                        'file' => $item->file
                    ];
                $this->images[] = asset($item->file);

                $this->empIds[] = $item->id;
            })->toArray();

        } else {
            $this->add();
        }


//        foreach ($this->employees as $program) {
//            $this->programsIds[] = ['id' => $program['id']];
//        }


    }

    public function remove($key)
    {
        if (array_key_exists('id', $this->employees[$key])) {
            $emp = About::find($this->employees[$key]['id']);
            Storage::delete($emp->file);
            $emp->delete();

            unset($this->empIds[$key]);
            $this->empIds = array_values($this->empIds);
        }
        unset($this->employees[$key]);
        $this->employees = array_values($this->employees);
    }

    public function add()
    {
        $this->employees[] = [
            'title_ru' => '',
            'title_en' => '',
            'content_ru' => '',
            'content_en' => '',
            'file' => ''
        ];


        $this->emit('itemAdded', count($this->employees) - 1);

    }


    public function store()
    {
        $validatedData = $this->validate();
        foreach ($this->employees as $key => $emp) {
            if (array_key_exists('id', $emp)) {
                $old = About::find($this->empIds[$key]);
                if (!is_string($emp['file'])) {
                    Storage::delete($old->file);
                    $imagePath = $emp['file']->store('uploads');
                    $validatedData['employees'][$key]['file'] = $imagePath;
                }
                $old->update($validatedData['employees'][$key]);
                $old->save();
            } else {
                $new = new About();
                $new->title_ru = $emp['title_ru'];
                $new->title_en = $emp['title_en'];
                $new->content_ru = $emp['title_ru'];
                $new->content_en = $emp['title_en'];
                $new->image = $emp['image'];
                $new->block = About::STAFF;
                $new->save();
            }
        }
        session()->flash('message', 'Успех!');
        Storage::deleteDirectory('livewire-tmp');
        return redirect()->route('admin.about.staff');
    }


}

app/Http/Livewire/AllArticlesComponent.php
<?php

namespace App\Http\Livewire;

use App\Models\Article;
use Illuminate\Support\Facades\Storage;
use Livewire\Component;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class AllArticlesComponent extends Component
{
    public $search;
    public $type;


    public function render()
    {
        $articles = $this->getAll();

        return view('livewire.all-articles-component', compact('articles'))->layout('admin.layouts.app');
    }

    protected function getAll()
    {
        if ($this->type == 'articles') {
            if ($this->search) {
                return Article::where('type', Article::ARTICLE)
                    ->where('title_ru', 'like', '%' . $this->search . '%')
                    ->orWhere('title_en', 'like', '%' . $this->search . '%')->paginate(10);
            }
            return Article::where('type', Article::ARTICLE)->paginate(10);
        } else {
            if ($this->search) {
                return Article::where('type', Article::NEWS)
                    ->where('title_ru', 'like', '%' . $this->search . '%')
                    ->orWhere('title_en', 'like', '%' . $this->search . '%')->paginate(10);
            }
            return Article::where('type', Article::NEWS)->paginate(10);
        }
    }

    public function mount($type)
    {
        throw_unless(in_array($type, ['articles', 'news']), NotFoundHttpException::class);
        $this->type = $type;
    }

    public function delete($id)
    {
        $article = Article::find($id);
        Storage::delete($article->image);
        $article->delete();
        session()->flash('message', 'Успех!');
    }

}

app/Http/Livewire/Home/FooterComponent.php
<?php

namespace App\Http\Livewire\Home;

use App\Models\Home;
use Livewire\Component;

class FooterComponent extends Component
{
    public $content_ru;
    public $content_en;
    public $footer;
    protected $rules = [
        'content_ru' => 'required|string',
        'content_en' => 'required|string',
    ];

    public function render()
    {
        return view('livewire.home.footer-component')->layout('admin.layouts.app');
    }

    public function mount()
    {
        $footer = Home::where('block', Home::FOOTER)->first();
        $this->footer = $footer;
        $this->content_ru = $footer->content_ru;
        $this->content_en = $footer->content_en;
    }

    public function store()
    {
        $this->footer->update($this->validate());
        session()->flash('message', 'Успех!');
    }
}

resources/views/livewire/all-articles-component.blade.php
<div>
    <div>
        @if (session()->has('message'))
            <div class="alert alert-success">
                {{ session('message') }}
            </div>
        @endif
    </div>
    <div class="form-group">
        <input type="text" class="form-control" wire:model="search"
               placeholder="Поиск"
        >
    </div>

    <div class="card">
        <div class="card-header">
            <div class="d-flex justify-content-between mt-3">
                <h2>{{$type=='articles'?'Статьи':'Новости'}}</h2>
                <a href="{{route('admin.article.create')}}" class="btn btn-success mb-2">Добавить</a>

            </div>
        </div>
        <div class="card-body">
            <div class="table table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Заголовок</th>
                        <th scope="col">Дата создания</th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody class="">
                    @foreach($articles as $index=>$article)
                        <tr>
                            <th scope="row"><a href="{{route('admin.article.edit',$article)}}">{{$index+1}} </a>
                            </th>
                            <td>
                                <a href="{{route('admin.article.edit',$article)}}">{{$article->title}}</a>
                            </td>
                            <td>
                                <a href="{{route('admin.article.edit',$article)}}">{{$article->created_at->format('d.m.Y H:i')}}</a>
                            </td>

                            <td>
                                <a href="{{route('admin.article.edit',$article)}}"><i
                                        class="fa fa-pen fa-fw"></i></a>
                            </td>
                            <td>
                                <a onclick="return confirm('Are you sure?')"
                                   href="#"
                                   wire:click="delete({{$article->id}})"><i
                                        class="fa fa-trash fa-fw"></i></a>
                            </td>

                        </tr>

                    @endforeach
                    </tbody>

                </table>

            </div>

        </div>
        <div class="card-footer">
            {{ $articles->links() }}
        </div>
    </div>


</div>

resources/views/livewire/content-component.blade.php
<div>
    <div class="card">
        <div class="card-header">
            <h1>Преимущества</h1>
        </div>

        <form wire:submit.prevent="store">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div>
                @if (session()->has('message'))
                    <div class="alert alert-success">
                        {{ session('message') }}
                    </div>
                @endif
            </div>

            @foreach($contents as $key=>$advantage)
                <div class="card-body  border border-bottom-1">
                    <div class="d-flex align-items-center">
                        <h3>Преимущество {{$key+1}}</h3>
                    </div>


                    @if($this->model=='App\Models\Everyone')
                    <div class="form-group">
                        <label class="label " for="title_ru">
                            Наименование
                        </label>
                        <div class="control">
                            <input type="text"
                                   class="form-control @error("contents.$key.title_ru") is-invalid @enderror"
                                   wire:model="contents.{{$key}}.title_ru"
                                   required>
                        </div>

                        @error("contents.$key.title_ru")
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label class="label " for="title_en">
                            Title
                        </label>
                        <div class="control">
                            <input type="text"
                                   class="form-control @error("contents.$key.title_en") is-invalid @enderror"
                                   wire:model="contents.{{$key}}.title_en"
                                   required>
                        </div>

                        @error("contents.$key.title_en")
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    @endif


                    <div class="form-group" wire:ignore>
                        <label class="label " for="content_ru">
                            Контент
                        </label>
                        <div class="control">
                        <textarea wire:model="contents.{{$key}}.content_ru"
                                  id="content_ru{{$key}}"
                                  class="form-control  @error("contents.$key.content_ru") is-invalid @enderror"
                                  required></textarea>
                        </div>

                        @error("contents.$key.content_ru")
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>

                    <div class="form-group" wire:ignore>
                        <label class="label " for="content_en">
                            Content
                        </label>
                        <div class="control">
                        <textarea wire:model="contents.{{$key}}.content_en"
                                  id="content_en{{$key}}"
                                  class="form-control  @error("contents.$key.content_en") is-invalid @enderror"
                                  required></textarea>
                        </div>

                        @error("contents.$key.content_en")
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>

                </div>
            @endforeach

            <div class="card-footer">
                <div class="form-group">
                    <div class="control">
                        <button
                            wire:loading.attr="disabled"
                            class="btn btn-success" type="submit">Сохранить
                        </button>
                        <div wire:loading>
                            Один момент...
                        </div>
                    </div>
                </div>
            </div>
        </form>

    </div>

</div>

@push('scripts')
    <script>
        let config = {
            filebrowserImageBrowseUrl: '/elfinder/ckeditor',
            allowedContent: true,
            removeFormatAttributes: ''
        };

        for (let i = 0; i <={{$key}}; i++) {
            CKEDITOR.replace('content_ru' + i, config);
            CKEDITOR.replace('content_en' + i, config);

            CKEDITOR.instances['content_en' + i].on('change', function (e) {
            @this.set('contents.' + i + '.content_en', e.editor.getData());
            });
            CKEDITOR.instances['content_ru' + i].on('change', function (e) {
            @this.set('contents.' + i + '.content_ru', e.editor.getData());
            });
        }
    </script>
@endpush

resources/views/livewire/prog-advantage-component.blade.php
<div>
    <div class="card">
        <div class="card-header">
            <h1>Преимущества</h1>
        </div>

        <form wire:submit.prevent="store">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div>
                @if (session()->has('message'))
                    <div class="alert alert-success">
                        {{ session('message') }}
                    </div>
                @endif
            </div>

            @foreach($advantages as $key=>$advantage)
                <div class="card-body  border border-bottom-1">
                    <div class="d-flex align-items-center">
                        <h3>Преимущество {{$key+1}}</h3>
                    </div>


                    <div class="form-group">
                        <label class="label " for="title_ru">
                            Наименование
                        </label>
                        <div class="control">
                            <input type="text"
                                   class="form-control @error("advantages.$key.title_ru") is-invalid @enderror"
                                   wire:model="advantages.{{$key}}.title_ru"
                                   required>
                        </div>

                        @error("advantages.$key.title_ru")
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label class="label " for="title">
                            Title
                        </label>
                        <div class="control">
                            <input type="text"
                                   class="form-control @error("advantages.$key.title_en") is-invalid @enderror"
                                   wire:model="advantages.{{$key}}.title_en"
                                   required>
                        </div>

                        @error("advantages.$key.title_en")
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>

                    <div class="form-group" wire:ignore>
                        <label class="label " for="content_ru">
                            Контент
                        </label>
                        <div class="control">
                        <textarea wire:model="advantages.{{$key}}.content_ru"
                                  id="content_ru{{$key}}"
                                  class="form-control  @error("advantages.$key.content_ru") is-invalid @enderror"
                                  required></textarea>
                        </div>

                        @error("advantages.$key.content_ru")
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>

                    <div class="form-group" wire:ignore>
                        <label class="label " for="content_en">
                            Content
                        </label>
                        <div class="control">
                        <textarea wire:model="advantages.{{$key}}.content_en"
                                  id="content_en{{$key}}"
                                  class="form-control  @error("advantages.$key.content_en") is-invalid @enderror"
                                  required></textarea>
                        </div>

                        @error("advantages.$key.content_en")
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>


                    <div class="form-group d-flex flex-column">
                        <label class="label d-block" for="icon">
                            Изобажение
                        </label>


                        @if ($advantages[$key]['image'])
                            Photo Preview:
                            <img src="{{ $advantages[$key]['image']->temporaryUrl() }}"
                                 style="max-width: 400px;object-fit: contain">
                        @elseif(array_key_exists('file',$advantages[$key]))
                            <img src="{{asset($advantages[$key]['file'])}}"
                                 style="max-width: 400px;object-fit: contain">
                        @endif

                        <input type="file" wire:model="advantages.{{$key}}.image">
                        @error("advantages.$key.image")
                        <div class="alert alert-danger">{{ $message }}</div> @enderror


                    </div>

                </div>
            @endforeach

            <div class="card-footer">
                <div class="form-group">
                    <div class="control">
                        <button
                            wire:loading.attr="disabled"
                            class="btn btn-success" type="submit">Сохранить
                        </button>
                        <div wire:loading>
                            Один момент...
                        </div>
                    </div>
                </div>
            </div>
        </form>

    </div>

</div>

@push('scripts')
    <script>
        let config = {
            filebrowserImageBrowseUrl: '/elfinder/ckeditor',
            allowedContent: true,
            removeFormatAttributes: ''
        };

        for (let i = 0; i <={{$key}}; i++) {
            CKEDITOR.replace('content_ru' + i, config);
            CKEDITOR.replace('content_en' + i, config);

            CKEDITOR.instances['content_en' + i].on('change', function (e) {
            @this.set('advantages.' + i + '.content_en', e.editor.getData());
            });
            CKEDITOR.instances['content_ru' + i].on('change', function (e) {
            @this.set('advantages.' + i + '.content_ru', e.editor.getData());
            });
        }
    </script>
@endpush